# Generated by Django 4.1.4 on 2022-12-13 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conteneur',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='inventaire.conteneur'),
        ),
    ]
