# Generated by Django 4.1.4 on 2022-12-13 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0003_alter_conteneur_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteneur',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='child', to='inventaire.conteneur'),
        ),
    ]
