# Generated by Django 4.1.4 on 2022-12-13 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0005_categorie_conteneur_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteneur',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteneur', to='inventaire.categorie'),
        ),
    ]
