# Generated by Django 4.1.4 on 2022-12-13 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0006_alter_conteneur_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
