# Generated by Django 4.1.4 on 2022-12-16 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventaire', '0007_categorie_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conteneur',
            name='categorie',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='conteneur', to='inventaire.categorie'),
        ),
    ]
